import react from 'react'
import Item from '../Item'
import Node from '../Node'
import { HSL } from '../Item'
import { MIN_ROTATION } from '../ItemEditor'
import { getCyclicValue } from '../../../util/MathTools'

export const DEFAULT_ANGLE = 10;
export const INCREMENT = 30; // the angle (in degrees) by which the angle of a new Ornament is increased when added to the same node.
export const DEFAULT_GAP = 2;
export const MIN_GAP = -9999
export const MAX_GAP = 9999
export const ROUNDING_DIGITS = 3


/**
 * An Ornament is an object representing an 'ornament', such as a label, attached to a Node. Ornaments do not have their own Z-indices.
 */
export default class Ornament extends Item {

    readonly node: Node // The node to which this Ornament is attached
    angle: number = DEFAULT_ANGLE // the preferred angle at which this Ornament is attached to this.node
    gap: number = DEFAULT_GAP
    gap100: number = DEFAULT_GAP

    width = 0;
    height = 0;

    /**
     * Creates a new Ornament that is then added to the supplied Node's array of Ornaments. The Ornament receives a unique ID, which is generated by
     * node.getNewOrnamentID().
     */
    constructor(node: Node) {
        const id = node.getNewOrnamentID();
        super(id);
        this.node = node;
        node.ornaments.push(this);
        const angle = DEFAULT_ANGLE + (node.ornaments.length - 1) * INCREMENT;
        this.angle = getCyclicValue(angle, MIN_ROTATION, 360, ROUNDING_DIGITS);
    }

    /**
     * Clones this Ornament. The clone is added to the supplied Node's array of Ornaments and receives a unique ID.
     */
    clone(node: Node) {
        const clone = new Ornament(node);
        this.copyValuesTo(clone);
        return clone;
    }

    protected copyValuesTo(target: Ornament) {
        target.group = this.group;
        target.isActiveMember = this.isActiveMember;
        target.angle = this.angle;
        target.gap = this.gap;
        target.gap100 = this.gap100;
    }

    getComponent(key: number, yOffset: number, unitscale: number, displayFontFactor: number, 
        primaryColor: HSL, markColor: string, 
        focus: boolean, selected: boolean, preselected: boolean, 
        onMouseDown: (item: Ornament, e: React.MouseEvent<HTMLDivElement, MouseEvent>) => void,
        onMouseEnter: (item: Ornament, e: React.MouseEvent<HTMLDivElement, MouseEvent>) => void,
        onMouseLeave: (item: Ornament, e: React.MouseEvent<HTMLDivElement, MouseEvent>) => void
    ): react.JSX.Element {
        return <></>;
    }    

}

export interface OrnamentCompProps {    
    yOffset: number
    unitscale: number
    displayFontFactor: number
    primaryColor: HSL
    markColor: string
    focus: boolean
    selected: boolean
    preselected: boolean
    onMouseDown: (item: Ornament, e: React.MouseEvent<HTMLDivElement, MouseEvent>) => void
    onMouseEnter: (item: Ornament, e: React.MouseEvent<HTMLDivElement, MouseEvent>) => void
    onMouseLeave: (item: Ornament, e: React.MouseEvent<HTMLDivElement, MouseEvent>) => void
}
