import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        modalbg: "rgba(var(--background-start-rgb))",       
        btnbg: "rgba(var(--btnbg))",
        btncolor: "rgba(var(--btncolor))",
        btnborder: "rgba(var(--btnborder))",
        btnhoverbg: "rgba(var(--btnhoverbg))",
        btnhovercolor: "rgba(var(--btnhovercolor))",
        btnactivebg: "rgba(var(--btnactivebg))",
        btnactivecolor: "rgba(var(--btnactivecolor))",
        btnfocusring: "rgba(var(--btnfocusring))",
        canvasbg: "rgba(var(--canvasbg))",
        canvasborder: "rgba(var(--canvasborder))",
        codepanelbg: "rgba(var(--codepanelbg))",
        codepanelcolor: "rgba(var(--codepanelcolor))",
        menuborder: "rgba(var(--menuborder))",
        textcolor: "rgba(var(--foreground-rgb))",
        tabselected: "rgba(var(--tabselected))",
        textfieldbg: "rgba(var(--textfieldbg))",
        textfieldcolor: "rgba(var(--textfieldcolor))",
      },
      typography: ({ theme }: {theme: any}) => ({
        light: {
          css: {
            '--tw-prose-body': theme('colors.slate.800'),
            '--tw-prose-headings': theme('colors.slate.900'),
            '--tw-prose-lead': theme('colors.slate.700'),
            '--tw-prose-links': theme('colors.slate.900'),
            '--tw-prose-bold': theme('colors.slate.900'),
            '--tw-prose-counters': theme('colors.slate.600'),
            '--tw-prose-bullets': theme('colors.slate.400'),
            '--tw-prose-hr': theme('colors.slate.300'),
            '--tw-prose-quotes': theme('colors.slate.900'),
            '--tw-prose-quote-borders': theme('colors.slate.300'),
            '--tw-prose-captions': theme('colors.slate.700'),
            '--tw-prose-code': theme('colors.slate.900'),
            '--tw-prose-kbd': theme('colors.slate.800'),
            '--tw-prose-pre-code': theme('colors.slate.100'),
            '--tw-prose-pre-bg': theme('colors.slate.900'),
            '--tw-prose-th-borders': theme('colors.slate.300'),
            '--tw-prose-td-borders': theme('colors.slate.200'),
            '--tw-prose-invert-body': theme('colors.slate.200'),
            '--tw-prose-invert-headings': theme('colors.white'),
            '--tw-prose-invert-lead': theme('colors.slate.300'),
            '--tw-prose-invert-links': theme('colors.white'),
            '--tw-prose-invert-bold': theme('colors.white'),
            '--tw-prose-invert-counters': theme('colors.slate.400'),
            '--tw-prose-invert-bullets': theme('colors.slate.600'),
            '--tw-prose-invert-hr': theme('colors.slate.700'),
            '--tw-prose-invert-quotes': theme('colors.slate.100'),
            '--tw-prose-invert-quote-borders': theme('colors.slate.700'),
            '--tw-prose-invert-captions': theme('colors.slate.400'),
            '--tw-prose-invert-code': theme('colors.white'),
            '--tw-prose-invert-pre-code': theme('colors.slate.300'),
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': theme('colors.slate.600'),
            '--tw-prose-invert-td-borders': theme('colors.slate.700'),
          },
        },
        dark: {
          css: {
            '--tw-prose-body': 'rgb(190, 169, 158)',
            '--tw-prose-headings': 'rgb(190, 169, 158)',
            '--tw-prose-lead': 'rgb(190, 169, 158)',
            '--tw-prose-links': 'rgb(190, 169, 158)',
            '--tw-prose-bold': 'rgb(190, 169, 158)',
            '--tw-prose-counters': 'rgb(190, 169, 158)',
            '--tw-prose-bullets': 'rgb(190, 169, 158)',
            '--tw-prose-hr': 'rgb(190, 169, 158)',
            '--tw-prose-quotes': 'rgb(190, 169, 158)',
            '--tw-prose-quote-borders': 'rgb(190, 169, 158)',
            '--tw-prose-captions': 'rgb(190, 169, 158)',
            '--tw-prose-code': 'rgb(190, 169, 158)',
            '--tw-prose-kbd': 'rgb(190, 169, 158)',
            '--tw-prose-pre-code': 'rgb(190, 169, 158)',
            '--tw-prose-pre-bg': 'rgba(23, 20, 16, 0.5)',
            '--tw-prose-th-borders': 'rgb(23, 20, 16)',
            '--tw-prose-td-borders': 'rgb(23, 20, 16)',
            '--tw-prose-invert-body': theme('colors.stone.200'),
            '--tw-prose-invert-headings': theme('colors.black'),
            '--tw-prose-invert-lead': theme('colors.stone.300'),
            '--tw-prose-invert-links': theme('colors.black'),
            '--tw-prose-invert-bold': theme('colors.black'),
            '--tw-prose-invert-counters': theme('colors.stone.400'),
            '--tw-prose-invert-bullets': theme('colors.stone.600'),
            '--tw-prose-invert-hr': theme('colors.stone.700'),
            '--tw-prose-invert-quotes': theme('colors.stone.100'),
            '--tw-prose-invert-quote-borders': theme('colors.stone.700'),
            '--tw-prose-invert-captions': theme('colors.stone.400'),
            '--tw-prose-invert-code': theme('colors.black'),
            '--tw-prose-invert-pre-code': theme('colors.stone.300'),
            '--tw-prose-invert-pre-bg': 'rgba(23, 20, 16, 0.5)',
            '--tw-prose-invert-th-borders': theme('colors.stone.600'),
            '--tw-prose-invert-td-borders': theme('colors.stone.700'),
          },
        },
      }),      
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};

export default config;
